#
# Copyright (c) 2024 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Disable the unspupported UART0 driver
CONFIG_NRFX_UARTE0=n

# Enable drivers for Snoozy peripherals
CONFIG_SPI=y
CONFIG_I2C=y
# TODO: Kconfig options for your specific sensor drivers